name: Build and Deploy to S3

# Only run action on closed PR to master branch
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    #Check out repo for use in build process 
    - uses: actions/checkout@v2

    #cd to site dir, install dependencies, build
    - name: Build app
      run: cd trainer-site && npm install && yarn build
    
    #Upload completed build dir for use in next step
    - uses: actions/upload-artifact@v2
      with:
        name: build-dir
        path: /home/runner/work/jeopardy-trainer/jeopardy-trainer/trainer-site/build
  
  #Time to deploy to S3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build-dir
        path: /home/runner/work/jeopardy-trainer/jeopardy-trainer/trainer-site/build
    - name: Deploy to s3 bucket
      run: cd /home/runner/work/jeopardy-trainer/jeopardy-trainer/trainer-site && aws s3 sync ./build s3://jprd.stevethiringer.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
